### ISSUE TITLE
Failure of finding variable coding resource

### ISSUE THREAD

**Issue by KeWXiong** [Dragonlongzhilin/RenalTumor#1]
Thanks for the contribution. I have trouble finding the resource of "variableFeatureSelection.R" in the project. Could the author update it? I would appreciate if the author could resolve it.

**Comment by Dragonlongzhilin** [comment]
Sorry, I left out this file. Thanks for your reminder.
I upload this file to "Functions" folder (https://github.com/Dragonlongzhilin/RenalTumor/tree/main/Functions).

**Comment by KeWXiong** [comment]
> Sorry, I left out this file. Thanks for your reminder. I upload this file to "Functions" folder (https://github.com/Dragonlongzhilin/RenalTumor/tree/main/Functions).

Thanks a plot!

**Comment by KeWXiong** [comment]
> Sorry, I left out this file. Thanks for your reminder. I upload this file to "Functions" folder (https://github.com/Dragonlongzhilin/RenalTumor/tree/main/Functions).

Thanks a lot!
