### ISSUE TITLE
absence of R code of FunctionsclusterProfiler.GSEA.R

### ISSUE THREAD

**Issue by zhangcy888** [Dragonlongzhilin/RenalTumor#2]
Dear Lin,

We notice that there are no codes related to the FunctionsclusterProfiler.GSEA.R in the step of cell identity annotation.
Could you please upload the file?

Best

**Comment by zhangcy888** [comment]
code related to Combined.P.FC.R  was also absent

**Comment by FFeiKong** [comment]
Dear Lin,
Thank you for your code. I would like to ask could you please upload the code of function "clusterProfiler.GSEA"?

Best regards
