### ISSUE TITLE
How much time required the FindAllMarkers for scATAC?

### ISSUE THREAD

**Issue by emanuelavilla** [Dragonlongzhilin/RenalTumor#3]
Hello!

I was reading your papers and got interested in the heatmap of the Z-score normalized accessibilities of scATAC-seq differential peaks for each cell type (like fig 1a). I looked at your code

cellType.DARs <- FindAllMarkers(scATAC.data, 
                                test.use = 'LR',
                                logfc.threshold=0, 
                                min.pct = 0.05, # often necessary to lower the min.pct threshold
                                latent.vars = "peak_region_fragments")

I was trying to use it for my data, but I found it extremely slow with the parameter you have used (the first of my cluster would take over 7 hours), so I used logfc.thrshold=0.25 and min.pct=0.25. 

My question is: this slowness is something you have met? If yes, how have you resolved it (for example, by using parallelization)?

**Comment by Dragonlongzhilin** [comment]
The calculation time is dependent on your computer or server configuration. Of course, we also adopted a parallel strategy to speed up the calculation. You can refer the parallel strategies provided by Signac team (https://stuartlab.org/signac/articles/future.html).
